### ISSUE TITLE
once the component is deleted, it should be deleted from database also

### ISSUE THREAD

**Issue by hank123** [hank123/hieapp#1]
current there has no implementation to delete a consumer/processor/producer if they are deleted from UI. need to add db persistent method(if it is not there yet)

**Comment by hank123** [comment]
look at this method in xplatform/src/main/java/com/accel/hie/controller/SubRouteController.java
not sure why it is not deleting... should use subRouteInfoBeanDao.deleteByNameAndNamespaceName method
public String deleteSubRoute(@RequestBody SubRouteInfoBean subRoute) throws Exception {
		
		System.out.println("name is -----------------"+ subRoute.getName());
		System.out.println("delete namespace is -----------------"+ subRoute.getNamespace().getName());
		//subRouteInfoBeanDao.delete(subRoute);
		subRouteInfoBeanDao.deleteByNameAndNamespaceName(subRoute.getName(), subRoute.getNamespace().getName());
	
		return "completed";
	}

**Comment by rpashikanti** [comment]
Fixed by removing URI options from Sub Route Info Bean.
