### ISSUE TITLE
add a button to add new "project" 

### ISSUE THREAD

**Issue by hank123** [hank123/hieapp#3]
project is called "namespace" internally by now, there has no way to add new project from UI, I am using SOAP UI to add new project, please add a button in the UI and use the REST API to add new project.

**Comment by hank123** [comment]
Please use existing method in SubRouteController.java:

public String addNamespace(@RequestBody Namespace namespace) throws Exception {
		
			
		
		namespaceDao.save(namespace);
	
		return "completed";
	}

public Iterable<Namespace> getNamespace() throws Exception {
		
			
		
		return namespaceDao.findAll();
	
		
	}

**Comment by rpashikanti** [comment]
add project functionality is implemented and tested
